/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author unova
 */


import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.awt.Color;
import javax.swing.JFileChooser;
import java.io.IOError;
import java.util.logging.Level;
import java.util.logging.Logger;




public class NepaliOCRui extends javax.swing.JFrame {
    Functions functions = new Functions();
    File newfile;
    Image scaledImage;
    BufferedImage image;
    BufferedImage tryimage;
    /**
     * Creates new form NepaliOCRui
     */
    public NepaliOCRui() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        binarizeButton = new javax.swing.JButton();
        detectSections = new javax.swing.JButton();
        okbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        nextbutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel() {
            protected void paintComponent(Graphics g){
                File testfile = new File("C:/Users/unova/Desktop/hello.jpg");
                if(tryimage!=null){
                    super.paintComponent(g);
                    scaledImage = tryimage.getScaledInstance(panel1.getWidth(),panel1.getHeight(),Image.SCALE_SMOOTH);
                    g.drawImage(scaledImage,0,0,null);
                }

            }
        };
        rotateLeft = new javax.swing.JButton();
        rotateRight = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        openrecent = new javax.swing.JMenu();
        close = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        help = new javax.swing.JMenu();
        helpContents = new javax.swing.JMenuItem();
        reportIssue = new javax.swing.JMenuItem();
        checkForUpdates = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("Detect Sections");

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/open24x24.png"))); // NOI18N
        openButton.setToolTipText("Open Image");
        openButton.setFocusable(false);
        openButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(openButton);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/diskette24x24.png"))); // NOI18N
        saveButton.setToolTipText("Save ");
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(saveButton);

        binarizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/binarize24x24.png"))); // NOI18N
        binarizeButton.setToolTipText("Binarize");
        binarizeButton.setFocusable(false);
        binarizeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        binarizeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        binarizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarizeButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(binarizeButton);

        detectSections.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/detectsections24x24.png"))); // NOI18N
        detectSections.setFocusable(false);
        detectSections.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        detectSections.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(detectSections);

        okbutton.setText("OK");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });

        cancelbutton.setText("Cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        nextbutton.setText("Next");
        nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonActionPerformed(evt);
            }
        });

        jButton2.setText("Previous");

        panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        rotateLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rotateleft24x24.png"))); // NOI18N
        rotateLeft.setToolTipText("Rotate Left");
        rotateLeft.setFocusable(false);
        rotateLeft.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rotateLeft.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rotateLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateLeftActionPerformed(evt);
            }
        });

        rotateRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rotateright24x24.png"))); // NOI18N
        rotateRight.setToolTipText("Rotate Right");
        rotateRight.setFocusable(false);
        rotateRight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rotateRight.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rotateRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateRightActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        file.setText("File");
        file.setToolTipText("");
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        file.add(open);

        openrecent.setText("Open Recent");
        file.add(openrecent);

        close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        close.setText("Close");
        file.add(close);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        save.setText("Save");
        file.add(save);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        file.add(exit);

        jMenuBar1.add(file);

        edit.setText("Edit");
        jMenuBar1.add(edit);

        help.setText("Help");

        helpContents.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        helpContents.setText("Help Contents");
        helpContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpContentsActionPerformed(evt);
            }
        });
        help.add(helpContents);

        reportIssue.setText("Report Issue");
        help.add(reportIssue);

        checkForUpdates.setText("Check For Updates");
        help.add(checkForUpdates);

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        help.add(about);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelbutton)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(rotateLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotateRight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextbutton)
                .addGap(120, 120, 120))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelbutton, nextbutton, okbutton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, panel1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rotateLeft, rotateRight});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rotateLeft)
                        .addComponent(rotateRight))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(nextbutton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okbutton)
                    .addComponent(cancelbutton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rotateLeft, rotateRight});

        pack();
    }// </editor-fold>//GEN-END:initComponents
// This is  a open from file option
    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        functions.openFile();
        this.newfile = functions.file1;
       try{
            tryimage = ImageIO.read(newfile);
        }catch(IOException aa){
            System.out.println("What");
        }
        if(newfile!=null){
       panel1.repaint();
        }
        
       
    }//GEN-LAST:event_openActionPerformed

    private void helpContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpContentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpContentsActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        // TODO add your handling code here:
        functions.openFile();
        this.newfile = functions.file1;
        try{
            tryimage = ImageIO.read(newfile);
        }catch(IOException aa){
            System.out.println("What");
        }
      if(newfile != null){
       panel1.repaint();
        }
        

        
    }//GEN-LAST:event_openButtonActionPerformed

    private void binarizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binarizeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_binarizeButtonActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_okbuttonActionPerformed

    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextbuttonActionPerformed

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void rotateLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateLeftActionPerformed
        // TODO add your handling code here:
        int height = tryimage.getHeight();
        int width = tryimage.getWidth();
        BufferedImage rotatedImage = new BufferedImage(height,width,tryimage.getType());
        for(int x=0;x<width;x++){
            for(int y=0; y<height;y++){
                rotatedImage.setRGB(y, width-x-1,tryimage.getRGB(x,y));
            }
        }
        
  
        try {
            ImageIO.write(rotatedImage,"png",new File("/home/shubhas/Desktop/binary.png"));
        } catch (IOException ex) {
            Logger.getLogger(NepaliOCRui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       tryimage = rotatedImage;
       panel1.repaint();
    }//GEN-LAST:event_rotateLeftActionPerformed

    private void rotateRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateRightActionPerformed
        // TODO add your handling code here:

         int height = tryimage.getHeight();
        int width = tryimage.getWidth();
        BufferedImage rotatedImage = new BufferedImage(height,width,tryimage.getType());
        for(int x=0;x<width;x++){
            for(int y=0; y<height;y++){
                rotatedImage.setRGB(height-y-1, x,tryimage.getRGB(x,y));
            }
        }
        
  
        try {
            ImageIO.write(rotatedImage,"png",new File("/home/shubhas/Desktop/binary.png"));
        } catch (IOException ex) {
            Logger.getLogger(NepaliOCRui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       tryimage = rotatedImage;
       panel1.repaint();
       
      
    }//GEN-LAST:event_rotateRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NepaliOCRui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NepaliOCRui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NepaliOCRui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NepaliOCRui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NepaliOCRui().setVisible(true);
            }
        });
    }
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JButton binarizeButton;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JMenuItem checkForUpdates;
    private javax.swing.JMenuItem close;
    private javax.swing.JButton detectSections;
    private javax.swing.JMenu edit;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JMenuItem helpContents;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton nextbutton;
    private javax.swing.JButton okbutton;
    private javax.swing.JMenuItem open;
    private javax.swing.JButton openButton;
    private javax.swing.JMenu openrecent;
    private javax.swing.JPanel panel1;
    private javax.swing.JMenuItem reportIssue;
    private javax.swing.JButton rotateLeft;
    private javax.swing.JButton rotateRight;
    private javax.swing.JMenuItem save;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    private void setColor(Color cyan) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
